apiVersion: v1
kind: Secret
metadata:
  name: {{ include "journal.fullname" . }}-db-secrets
  labels:
    {{- include "journal.labels" . | nindent 4 }}
type: Opaque
stringData:
  # SQL Server SA Password
  {{- if .Values.sqlserver.enabled }}
  sqlserver-sa-password: {{ .Values.sqlserver.auth.saPassword | quote }}
  {{- end }}
  # PostgreSQL Password
  {{- if .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
  {{- end }}
  # MongoDB Root Password
  {{- if .Values.mongodb.enabled }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | quote }}
  {{- end }}
  # OpenSearch Admin Password
  {{- if .Values.opensearch.enabled }}
  opensearch-admin-password: {{ (index .Values.opensearch.extraEnvs 0).value | quote }}
  {{- end }}
