apiVersion: v1
kind: Service
metadata:
  name: {{ include "journal.fullname" . }}
  labels:
    {{- include "journal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.journal.service.type }}
  ports:
    - port: {{ .Values.journal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "journal.selectorLabels" . | nindent 4 }}
